
name: 'CI-UnitTest'

jobs:
- template: job_template.yml
  parameters:
    os: 'Linux'
    python_version: '3.5'

#- template: job_template.yml
#  parameters:
#    os: 'Linux'
#    python_version: '3.6'