
jobs:
- template: 'job_template.yml'
  parameters:
    os: 'Linux'
    python_version:
    - 'cp3.5'
    - 'cp3.6'

#- template: job_template.yml
#  parameters:
#    os: 'Linux'
#    python_version: '3.6'