
jobs:
- template: 'job_matrix_generator.yml'
  parameters:
    platforms:
    - 'Linux'
    - 'Windows'
    - 'MacOS'
    python_versions: ['3.5', '3.6']
    tf_versions: ['1.11']
    onnx_versions: ['1.2', '1.3']
    onnx_backends:
      onnxruntime: ['0.1.3', '0.1.4']
      caffe2: ['']

    job:
      steps:
      - bash: echo 'hello1'
        displayName: 'Hello World1'

      - template: 'unit_test.yml'

      - bash: echo 'hello3'
        displayName: 'Hello World3'