
jobs:
- template: 'job_template.yml'
  parameters:
    platforms:
      - 'Linux'
      - 'Windows'
      - 'MacOS'
    python_versions: ['3.5', '3.6']
    tf_versions: ['1.12', '1.11']
    onnx_versions: ['1.2', '1.3']
    onnx_backends:
      onnxruntime: ['0.1.3', '0.1.4']
      caffe2: ['']

