parameters:
  name: ''
  os: ''
  python_versions: {}

jobs:
- ${{ each pair in parameters.python_versions }}:
  - job: ${{ pair.key }}
    pool:
      ${{ if eq(parameters.os, 'Linux') }}:
        vmImage: ubuntu-16.04
      ${{ if eq(parameters.os, 'Windows') }}:
        vmImage: vs2017-win2016
      ${{ if eq(parameters.os, 'macOS') }}:
        vmImage: macOS-10.13
    steps:
    - bash: echo ${{ pair.value }}
      displayName: 'hello'

#  - bash: |
#      echo 'hello world'
#    displayName: 'hello'
#  - ${{ if eq(parameters.name, '') }}:
#    - bash: echo '!!!!!'


