parameters:
  name: ''
  os: []
  python_version: ''

jobs:
- ${{ each os in parameters.os }}:
  - job: ${{ parameters.name }}
  pool:
    ${{ if eq(os, 'Linux') }}:
      vmImage: ubuntu-16.04
    ${{ if eq(os, 'Windows') }}:
      vmImage: vs2017-win2016
    ${{ if eq(os, 'macOS') }}:
      vmImage: macOS-10.13
  steps:
  - bash: |
      echo 'hello world'
    displayName: 'hello'
#  - ${{ if eq(parameters.name, '') }}:
#    - bash: echo '!!!!!'


