parameters:
  name: ''
  platforms: []
  python_versions: {}

jobs:
- ${{ each platform in parameters.platforms }}:
  - job: ${{ platform }}
    pool:
      ${{ if eq(platform, 'Linux') }}:
        vmImage: ubuntu-16.04
      ${{ if eq(platform, 'Windows') }}:
        vmImage: vs2017-win2016
      ${{ if eq(platform, 'macOS') }}:
        vmImage: macOS-10.13
    strategy:
      matrix:
        ${{ each python_version in parameters.python_versions }}:
          ${{ format('Python{0}', python_version) }}:
            ${{ format('AP_PYTHON_VERSION{0}', python_version) }}: '${{ python_version }}'

    steps:
    - bash: echo 'hello'
      displayName: 'hello'
