parameters:
  name: ''
  platforms: []
  python_versions: {}

jobs:
- ${{ each platform in parameters.platforms }}:
  - job: ${{ platform }}
    pool:
      ${{ if eq(platform, 'Linux') }}:
        vmImage: ubuntu-16.04
      ${{ if eq(platform, 'Windows') }}:
        vmImage: vs2017-win2016
      ${{ if eq(platform, 'macOS') }}:
        vmImage: macOS-10.13
    strategy:
      matrix:
        ${{ each pair in parameters.python_versions }}:
          ${{ pair.key }}:
            ${{ pair.key }}: '${{ pair.value }}'
#        Python3.5:
#          PYTHON_VERSION: '3.5'
#        Python3.6:
#          PYTHON_VERSION: '3.6'

    steps:
    - bash: echo 'hello'
      displayName: 'hello'
