parameters:
  name: ""
  os: ""
  python_version: ""

jobs:
- ${{ if eq(parameters.name, '') }}:
    job: ${{ parameters.os }}
- ${{ if ne(parameters.name, '') }}:
    job: ${{ parameters.name }}
    
  pool:
    vmImage: "ubuntu-16.04"
  steps:
  - bash: |
      echo "hello world"
    displayName: "hello"

