parameters:
  name: ''
  os: ''
  python_version: ''

jobs:
- job: ${{ parameters.os }}
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: |
      echo 'hello world'
    displayName: 'hello'
  - ${{ if eq(parameters.name, '') }}:
    - bash: echo '!!!!!'


