parameters:
  name: ''
  platforms: []
  python_versions: ['3.6']
  tf_versions: ['']
  onnx_versions: ['']

jobs:
- ${{ each platform in parameters.platforms }}:
  - job: ${{ platform }}
    pool:
      ${{ if eq(platform, 'Linux') }}:
        vmImage: ubuntu-16.04
      ${{ if eq(platform, 'Windows') }}:
        vmImage: vs2017-win2016
      ${{ if eq(platform, 'macOS') }}:
        vmImage: macOS-10.13
    strategy:
      matrix:
        ${{ each python_version in parameters.python_versions }}:
          ${{ each tf_version in parameters.tf_versions }}:
            ${{ each onnx_version in parameters.onnx_versions }}:
              ${{ format('Python{0}_TF{1}_Onnx{2}', python_version, tf_version, onnx_version) }}:
                ${{ format('AP_PYTHON_VERSION{0}', python_version) }}: '${{ python_version }}'
                ${{ format('AP_TF_VERSION{0}', tf_version) }}: '${{ tf_version }}'
                ${{ format('AP_ONNX_VERSION{0}', onnx_version) }}: '${{ onnx_version }}'

    steps:
    - bash: env
      displayName: 'env'
