parameters:
  name: ''
  platforms: []
  python_versions: {}

jobs:
- ${{ each platform in parameters.platforms }}:
  - job: ${{ platform }}
    pool:
      ${{ if eq(platform, 'Linux') }}:
        vmImage: ubuntu-16.04
      ${{ if eq(platform, 'Windows') }}:
        vmImage: vs2017-win2016
      ${{ if eq(platform, 'macOS') }}:
        vmImage: macOS-10.13
    steps:
    - bash: echo 'hello'
      displayName: 'hello'
