parameters:
  name: ''
  os: ''
  python_version: []

jobs:
- job: ${{ parameters.name }}
#- ${{ each os in parameters.os }}:
#  - job: ${{ parameters.name }}
  pool:
    ${{ if eq(parameters.os, 'Linux') }}:
      vmImage: ubuntu-16.04
    ${{ if eq(parameters.os, 'Windows') }}:
      vmImage: vs2017-win2016
    ${{ if eq(parameters.os, 'macOS') }}:
      vmImage: macOS-10.13
  steps:
  -  ${{ each python_version in parameters.python_version }}:
    - bash: |
        echo ${{ python_version }}
      displayName: 'hello'

#  - bash: |
#      echo 'hello world'
#    displayName: 'hello'
#  - ${{ if eq(parameters.name, '') }}:
#    - bash: echo '!!!!!'


